# Docker Compose 基础配置 - 使用Docker Hub预构建镜像
# 适用于快速部署和生产环境
version: '3.8'

services:
  web-image-processor:
    image: aqbjqtd/web-image-processor:latest
    container_name: web-image-processor
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - NODE_ENV=production
      - TZ=${TZ:-Asia/Shanghai}
    networks:
      - web-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  web-network:
    driver: bridge