services:
  web-image-processor:
    image: aqbjqtd/web-image-processor:latest
    container_name: web-image-processor
    restart: unless-stopped
    ports:
      - "59000:80"
    environment:
      - TZ=Asia/Shanghai
    # 健康检查 - 简化版本，兼容性更好
    healthcheck:
      test: ["CMD-SHELL", "netstat -tln | grep :80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-image-processor.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.web-image-processor.tls.certresolver=letsencrypt"
      - "traefik.http.services.web-image-processor.loadbalancer.server.port=80"
    # 资源限制 - 适合低配置VPS
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'