services:
  web-image-processor:
    image: aqbjqtd/web-image-processor:latest
    container_name: web-image-processor
    restart: unless-stopped
    # 此处网络我是为了适配1panel平台，你也可以改成其它
    networks:
      - 1panel-network
    ports:
      - "59000:80"
    environment:
      - TZ=Asia/Shanghai
    # 健康检查 - 简化版本，兼容性更好
    healthcheck:
      test: ["CMD-SHELL", "netstat -tln | grep :80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      
# 此处网络我是为了适配1panel平台，你也可以改成其它
networks:
  1panel-network:
    external: true